# Generated by Django 6.0.5 on 2026-06-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name': 'Catagory', 'verbose_name_plural': 'Catagories'},
        ),
    ]
